upstream keycloak_backend {
    ip_hash;
    server keycloak-1:8080;
    server keycloak-2:8180;
#    server keycloak-3:8280;
}

server {
    listen 127.0.0.1:8081;

    location = /health {
        access_log off;
        return 200 "healthy\n";
    }
}

server {
    listen 80;
    server_name local-auth;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name local-auth;

    ssl_certificate     /etc/nginx/certs/local-auth.crt;
    ssl_certificate_key /etc/nginx/certs/local-auth.key;

    location / {
        proxy_pass http://keycloak_backend;
        proxy_http_version 1.1;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  443;

#         proxy_ssl_server_name on;
#         proxy_ssl_verify off;
    }
}